-- AlterTable
ALTER TABLE "dataAnalytics" ALTER COLUMN "totalQuantityPurchased" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avgDailyUsed" SET DEFAULT 0,
ALTER COLUMN "avgDailyUsed" SET DATA TYPE DOUBLE PRECISION;
